name: XeraMonitor
version: 1.0.0
main: Xera.Monitor.XeraMonitor
api-version: 1.16
authors: [Nate Legault, Pistonmaster]
description: Display your server in the Web!
commands:
  xtmreload:
    permission: xtm.admin
